// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckeujatzqqmlntrwhcjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrZXVqYXR6cXFtbG50cndoY2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMjUwMzYsImV4cCI6MjA3MDkwMTAzNn0.f5KCPwlj8HAmcUj_K2V5iCpH5CTomPh9byJhUHU-0Rc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});